const Keys = {
  GRAVEKEEPER: 'GRAVEKEEPER',
  ARMOR: 'FLYING ARMOR',
  MALPHAS: 'MALPHAS',
  SLIDE: 'SKELETON BLAZE',
  UNDINE: 'UNDINE',
  SKULA: 'SKULA',
  BAT: 'BAT',
  HIPPOGRYPH: 'HIPPOGRYPH',
  RED: 'RED',
  BLUE: 'BLUE',
  YELLOW: 'YELLOW',
  REDBOOK: 'RED BOOK',
  BLUEBOOK: 'BLUE BOOK',
  YELLOWBOOK: 'YELLOW BOOK',
  MANTICORE: 'MANTICORE',
  CURLY: 'CURLY',
  DEVIL: 'DEVIL',
  PANTHER: 'BLACK PANTHER',
  GALAMOTH: 'GALAMOTH',
};

module.exports = Keys;
